// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: actor-framework/remote/proto/actor.proto

package remote

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	TypeName      string                 `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteMessage) Reset() {
	*x = RemoteMessage{}
	mi := &file_actor_framework_remote_proto_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteMessage) ProtoMessage() {}

func (x *RemoteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_actor_framework_remote_proto_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteMessage.ProtoReflect.Descriptor instead.
func (*RemoteMessage) Descriptor() ([]byte, []int) {
	return file_actor_framework_remote_proto_actor_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteMessage) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *RemoteMessage) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *RemoteMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_actor_framework_remote_proto_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_actor_framework_remote_proto_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_actor_framework_remote_proto_actor_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GossipProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Members       []*NodeInfo            `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipProto) Reset() {
	*x = GossipProto{}
	mi := &file_actor_framework_remote_proto_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipProto) ProtoMessage() {}

func (x *GossipProto) ProtoReflect() protoreflect.Message {
	mi := &file_actor_framework_remote_proto_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipProto.ProtoReflect.Descriptor instead.
func (*GossipProto) Descriptor() ([]byte, []int) {
	return file_actor_framework_remote_proto_actor_proto_rawDescGZIP(), []int{2}
}

func (x *GossipProto) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *GossipProto) GetMembers() []*NodeInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_actor_framework_remote_proto_actor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_actor_framework_remote_proto_actor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_actor_framework_remote_proto_actor_proto_rawDescGZIP(), []int{3}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *NodeInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_actor_framework_remote_proto_actor_proto protoreflect.FileDescriptor

const file_actor_framework_remote_proto_actor_proto_rawDesc = "" +
	"\n" +
	"(actor-framework/remote/proto/actor.proto\x12\x06remote\"a\n" +
	"\rRemoteMessage\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x1b\n" +
	"\ttype_name\x18\x02 \x01(\tR\btypeName\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"5\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"V\n" +
	"\vGossipProto\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12*\n" +
	"\amembers\x18\x02 \x03(\v2\x10.remote.NodeInfoR\amembers\"o\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion2\x9b\x01\n" +
	"\fActorService\x12*\n" +
	"\x04Tell\x12\x15.remote.RemoteMessage\x1a\v.remote.Ack\x123\n" +
	"\x03Ask\x12\x15.remote.RemoteMessage\x1a\x15.remote.RemoteMessage\x12*\n" +
	"\x06Gossip\x12\x13.remote.GossipProto\x1a\v.remote.AckB(Z&agentskiSistemi/actor-framework/remoteb\x06proto3"

var (
	file_actor_framework_remote_proto_actor_proto_rawDescOnce sync.Once
	file_actor_framework_remote_proto_actor_proto_rawDescData []byte
)

func file_actor_framework_remote_proto_actor_proto_rawDescGZIP() []byte {
	file_actor_framework_remote_proto_actor_proto_rawDescOnce.Do(func() {
		file_actor_framework_remote_proto_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actor_framework_remote_proto_actor_proto_rawDesc), len(file_actor_framework_remote_proto_actor_proto_rawDesc)))
	})
	return file_actor_framework_remote_proto_actor_proto_rawDescData
}

var file_actor_framework_remote_proto_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_actor_framework_remote_proto_actor_proto_goTypes = []any{
	(*RemoteMessage)(nil), // 0: remote.RemoteMessage
	(*Ack)(nil),           // 1: remote.Ack
	(*GossipProto)(nil),   // 2: remote.GossipProto
	(*NodeInfo)(nil),      // 3: remote.NodeInfo
}
var file_actor_framework_remote_proto_actor_proto_depIdxs = []int32{
	3, // 0: remote.GossipProto.members:type_name -> remote.NodeInfo
	0, // 1: remote.ActorService.Tell:input_type -> remote.RemoteMessage
	0, // 2: remote.ActorService.Ask:input_type -> remote.RemoteMessage
	2, // 3: remote.ActorService.Gossip:input_type -> remote.GossipProto
	1, // 4: remote.ActorService.Tell:output_type -> remote.Ack
	0, // 5: remote.ActorService.Ask:output_type -> remote.RemoteMessage
	1, // 6: remote.ActorService.Gossip:output_type -> remote.Ack
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_actor_framework_remote_proto_actor_proto_init() }
func file_actor_framework_remote_proto_actor_proto_init() {
	if File_actor_framework_remote_proto_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actor_framework_remote_proto_actor_proto_rawDesc), len(file_actor_framework_remote_proto_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_actor_framework_remote_proto_actor_proto_goTypes,
		DependencyIndexes: file_actor_framework_remote_proto_actor_proto_depIdxs,
		MessageInfos:      file_actor_framework_remote_proto_actor_proto_msgTypes,
	}.Build()
	File_actor_framework_remote_proto_actor_proto = out.File
	file_actor_framework_remote_proto_actor_proto_goTypes = nil
	file_actor_framework_remote_proto_actor_proto_depIdxs = nil
}
