// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: actor-framework/remote/proto/actor.proto

package remote

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActorService_Tell_FullMethodName   = "/remote.ActorService/Tell"
	ActorService_Ask_FullMethodName    = "/remote.ActorService/Ask"
	ActorService_Gossip_FullMethodName = "/remote.ActorService/Gossip"
)

// ActorServiceClient is the client API for ActorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActorServiceClient interface {
	Tell(ctx context.Context, in *RemoteMessage, opts ...grpc.CallOption) (*Ack, error)
	Ask(ctx context.Context, in *RemoteMessage, opts ...grpc.CallOption) (*RemoteMessage, error)
	Gossip(ctx context.Context, in *GossipProto, opts ...grpc.CallOption) (*Ack, error)
}

type actorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActorServiceClient(cc grpc.ClientConnInterface) ActorServiceClient {
	return &actorServiceClient{cc}
}

func (c *actorServiceClient) Tell(ctx context.Context, in *RemoteMessage, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ActorService_Tell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actorServiceClient) Ask(ctx context.Context, in *RemoteMessage, opts ...grpc.CallOption) (*RemoteMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoteMessage)
	err := c.cc.Invoke(ctx, ActorService_Ask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actorServiceClient) Gossip(ctx context.Context, in *GossipProto, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ActorService_Gossip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActorServiceServer is the server API for ActorService service.
// All implementations must embed UnimplementedActorServiceServer
// for forward compatibility.
type ActorServiceServer interface {
	Tell(context.Context, *RemoteMessage) (*Ack, error)
	Ask(context.Context, *RemoteMessage) (*RemoteMessage, error)
	Gossip(context.Context, *GossipProto) (*Ack, error)
	mustEmbedUnimplementedActorServiceServer()
}

// UnimplementedActorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActorServiceServer struct{}

func (UnimplementedActorServiceServer) Tell(context.Context, *RemoteMessage) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Tell not implemented")
}
func (UnimplementedActorServiceServer) Ask(context.Context, *RemoteMessage) (*RemoteMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedActorServiceServer) Gossip(context.Context, *GossipProto) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Gossip not implemented")
}
func (UnimplementedActorServiceServer) mustEmbedUnimplementedActorServiceServer() {}
func (UnimplementedActorServiceServer) testEmbeddedByValue()                      {}

// UnsafeActorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActorServiceServer will
// result in compilation errors.
type UnsafeActorServiceServer interface {
	mustEmbedUnimplementedActorServiceServer()
}

func RegisterActorServiceServer(s grpc.ServiceRegistrar, srv ActorServiceServer) {
	// If the following call panics, it indicates UnimplementedActorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActorService_ServiceDesc, srv)
}

func _ActorService_Tell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorServiceServer).Tell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActorService_Tell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorServiceServer).Tell(ctx, req.(*RemoteMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActorService_Ask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorServiceServer).Ask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActorService_Ask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorServiceServer).Ask(ctx, req.(*RemoteMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActorService_Gossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorServiceServer).Gossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActorService_Gossip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorServiceServer).Gossip(ctx, req.(*GossipProto))
	}
	return interceptor(ctx, in, info, handler)
}

// ActorService_ServiceDesc is the grpc.ServiceDesc for ActorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote.ActorService",
	HandlerType: (*ActorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tell",
			Handler:    _ActorService_Tell_Handler,
		},
		{
			MethodName: "Ask",
			Handler:    _ActorService_Ask_Handler,
		},
		{
			MethodName: "Gossip",
			Handler:    _ActorService_Gossip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "actor-framework/remote/proto/actor.proto",
}
